configatron.gcm_on_rails.api_url = 'https://android.googleapis.com/gcm/send'
configatron.gcm_on_rails.api_key = 'AIzaSyAWWpi4aFtAnaF65EOGuNc-D_300g_fuiE'
configatron.gcm_on_rails.app_name = 'com.riotapps.word'
configatron.gcm_on_rails.delivery_format = 'json'
configatron.gcm_on_rails.sender_id = '505875093616'